name: CI

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to GitHub container registry
          uses: docker/login-action@v1.10.0
          with:
            registry: demovivo.azurecr.io
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

        - name: Lowercase the repo name and username
          run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

        - name: Build and push container image to ACR Registry
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: demovivo.azurecr.io/${{ env.REPO }}:${{ github.sha }}
            file: ./Dockerfile

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
        - name: Azure Login
          uses: azure/login@v1
          with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Deploy to containerapp
          uses: azure/CLI@v1
          with:
              inlineScript: |
                az config set extension.use_dynamic_install=yes_without_promt
                az containerapp registry set -n demo-container -g demo-container --server demovivo.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
                az containerapp update -n demo-container -g demo-container --cpu 2 --memory 4Gi
                az containerapp update -n demo-container -g demo-container --image demovivo.azurecr.io/thevivotran/huggingface-azure-acr:${{ github.sha }}
                


                
